import Link from 'next/link';

export default function TermsOfService() {
    return (
        <div style={{
            width: '100vw',
            minHeight: '100vh',
            backgroundImage: 'url("/aesthetics/Foyer.jpg")',
            backgroundSize: 'cover',
            backgroundPosition: 'center',
            backgroundAttachment: 'fixed',
            paddingTop: 'var(--space-2xl)',
            paddingBottom: 'var(--space-3xl)'
        }}>
            <div className="container container-narrow card animate-fade-in" style={{ backgroundColor: 'rgba(253, 248, 240, 0.95)' }}>
                <h1 className="text-display" style={{ fontSize: '2.5rem', marginBottom: 'var(--space-lg)' }}>Terms of Service</h1>

                <div style={{ fontFamily: 'var(--font-body)', lineHeight: 1.6, color: 'var(--ink)' }}>
                    <p><strong>Effective Date:</strong> March 2026</p>

                    <h2 className="text-display" style={{ fontSize: '1.5rem', marginTop: 'var(--space-lg)', marginBottom: 'var(--space-sm)' }}>1. Acceptance of Terms</h2>
                    <p>By accessing or using The Ton, you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you may not access the service.</p>

                    <h2 className="text-display" style={{ fontSize: '1.5rem', marginTop: 'var(--space-lg)', marginBottom: 'var(--space-sm)' }}>2. Age Restriction (16+)</h2>
                    <p><strong>You must be at least 16 years of age to use this service.</strong> By creating an account and using The Ton, you warrant that you are at least 16 years old. If we discover that a user is under 16, their account and associated data will be immediately deleted.</p>

                    <h2 className="text-display" style={{ fontSize: '1.5rem', marginTop: 'var(--space-lg)', marginBottom: 'var(--space-sm)' }}>3. Conduct and Content Guidelines</h2>
                    <p>The Ton is designed for fun, anonymous society updates. Abusive behavior will not be tolerated. You agree NOT to post whispers that:</p>
                    <ul>
                        <li>Contain hate speech, slurs, or derogatory remarks.</li>
                        <li>Promote violence, illegal acts, or self-harm.</li>
                        <li>Constitute targeted bullying, harassment, or severe profanity.</li>
                        <li>Share private, non-consensual identifiable information about others (doxxing).</li>
                    </ul>

                    <h2 className="text-display" style={{ fontSize: '1.5rem', marginTop: 'var(--space-lg)', marginBottom: 'var(--space-sm)' }}>4. AI Content and Moderation</h2>
                    <p><strong>Content Scanning:</strong> All submitted whispers are strictly monitored by AI models to ensure compliance with our content guidelines. Violations will result in your whisper being blocked, a "strike" recorded against your account, and potential banishment from the platform.</p>
                    <p><strong>AI Generation:</strong> The society papers distributed in this app are generated by Artificial Intelligence based on user-submitted content. The Ton acts as a platform and is not responsible for the creative outputs generated by the AI from user submissions.</p>

                    <h2 className="text-display" style={{ fontSize: '1.5rem', marginTop: 'var(--space-lg)', marginBottom: 'var(--space-sm)' }}>5. Built for Trust: European Privacy by Design</h2>
                    <p>Social apps today often treat user data as a commodity. We wanted The Ton to be different. Because our platform is fundamentally built on anonymity and AI generation, we engineered our architecture from the ground up to comply with the strictest privacy laws in the world: the EU's GDPR, Digital Services Act (DSA), and the AI Act.</p>
                    <ul>
                        <li style={{ marginBottom: '0.5rem' }}><strong>Anonymity & AI Safety:</strong> All whispers are passed through an advanced AI Moderation filter before they are accepted. If a user submits abusive content (hate speech, bullying, etc.), the database quietly reports their behavior in the system.</li>
                        <li style={{ marginBottom: '0.5rem' }}><strong>Manual Data Processing (GDPR):</strong> Our users have the legal Right to Erasure and Data Portability. When a user requests to delete their account or export their data on the Settings page, it securely logs the request in our internal administrative system. Our administrators then have a 30-day legal window to process these requests.</li>
                        <li style={{ marginBottom: '0.5rem' }}><strong>AI Transparency:</strong> Every Society letter generated by Lady Whistledown is explicitly signed with an AI notification, ensuring full compliance with the European AI Act's transparency requirements.</li>
                    </ul>

                    <h2 className="text-display" style={{ fontSize: '1.5rem', marginTop: 'var(--space-lg)', marginBottom: 'var(--space-sm)' }}>6. Reporting</h2>
                    <p>If you encounter content or societies that violate these terms, please use the <strong>Report Society or Content</strong> button found on the relevant group page. To ensure your safety and privacy, reports are written directly to our internal administrative database for immediate review.</p>

                    <div style={{ marginTop: 'var(--space-xl)', paddingTop: 'var(--space-md)', borderTop: '1px solid var(--cloud)' }}>
                        <Link href="/" style={{ color: 'var(--wisteria)', textDecoration: 'underline' }}>Return to the Foyer</Link>
                    </div>
                </div>
            </div>
        </div>
    );
}
