import Link from 'next/link';

export default function TermsOfService() {
    return (
        <div style={{
            width: '100vw',
            minHeight: '100vh',
            backgroundImage: 'url("/aesthetics/Foyer.jpg")',
            backgroundSize: 'cover',
            backgroundPosition: 'center',
            backgroundAttachment: 'fixed',
            paddingTop: 'var(--space-2xl)',
            paddingBottom: 'var(--space-3xl)'
        }}>
            <div className="container container-narrow card animate-fade-in" style={{ backgroundColor: 'rgba(253, 248, 240, 0.95)' }}>
                <h1 className="text-display" style={{ fontSize: '2.5rem', marginBottom: 'var(--space-lg)' }}>Terms of Service</h1>

                <div style={{ fontFamily: 'var(--font-body)', lineHeight: 1.6, color: 'var(--ink)' }}>
                    <p><strong>Effective Date:</strong> March 2026</p>

                    <h2 className="text-display" style={{ fontSize: '1.5rem', marginTop: 'var(--space-lg)', marginBottom: 'var(--space-sm)' }}>1. Acceptance of Terms</h2>
                    <p>By accessing or using The Ton, you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you may not access the service.</p>

                    <h2 className="text-display" style={{ fontSize: '1.5rem', marginTop: 'var(--space-lg)', marginBottom: 'var(--space-sm)' }}>2. Age Restriction (16+)</h2>
                    <p><strong>You must be at least 16 years of age to use this service.</strong> By creating an account and using The Ton, you warrant that you are at least 16 years old. If we discover that a user is under 16, their account and associated data will be immediately deleted.</p>

                    <h2 className="text-display" style={{ fontSize: '1.5rem', marginTop: 'var(--space-lg)', marginBottom: 'var(--space-sm)' }}>3. Conduct and Content Guidelines</h2>
                    <p>The Ton is designed for fun, anonymous society updates. Abusive behavior will not be tolerated. You agree NOT to post whispers that:</p>
                    <ul>
                        <li>Contain hate speech, slurs, or derogatory remarks.</li>
                        <li>Promote violence, illegal acts, or self-harm.</li>
                        <li>Constitute targeted bullying, harassment, or severe profanity.</li>
                        <li>Share private, non-consensual identifiable information about others (doxxing).</li>
                    </ul>

                    <h2 className="text-display" style={{ fontSize: '1.5rem', marginTop: 'var(--space-lg)', marginBottom: 'var(--space-sm)' }}>4. AI Content and Moderation</h2>
                    <p><strong>Content Scanning:</strong> All submitted whispers are strictly monitored by AI models to ensure compliance with our content guidelines. Violations will result in your whisper being blocked, a "strike" recorded against your account, and potential banishment from the platform.</p>
                    <p><strong>AI Generation:</strong> The society papers distributed in this app are generated by Artificial Intelligence based on user-submitted content. The Ton acts as a platform and is not responsible for the creative outputs generated by the AI from user submissions.</p>

                    <h2 className="text-display" style={{ fontSize: '1.5rem', marginTop: 'var(--space-lg)', marginBottom: 'var(--space-sm)' }}>5. Reporting</h2>
                    <p>If you encounter content or societies that violate these terms, please use the "Report Society" link found on the relevant group page to notify administration.</p>

                    <div style={{ marginTop: 'var(--space-xl)', paddingTop: 'var(--space-md)', borderTop: '1px solid var(--cloud)' }}>
                        <Link href="/" style={{ color: 'var(--wisteria)', textDecoration: 'underline' }}>Return to the Foyer</Link>
                    </div>
                </div>
            </div>
        </div>
    );
}
